### ISSUE TITLE
Theme color pallet not fully appearing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/pexcon#1]
The theme color pallet is not fully visible when we try to change the color of the theme : 
https://prnt.sc/uujfr1

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
